name: MoodAuth
version: 1.0
main: fr.moodcraft.auth.Main
api-version: '1.21'
author: MoodCraft

commands:
  login:
    description: Connexion au compte MoodCraft
    usage: /login <motdepasse>
  register:
    description: Création du compte MoodCraft
    usage: /register <motdepasse>
  changepassword:
    description: Changer son mot de passe
    usage: /changepassword <ancien> <nouveau>
  resetcompte:
    description: Réinitialiser le compte d'un joueur
    usage: /resetcompte <joueur>
  authadmin:
    description: Administration MoodAuth
    usage: /authadmin
    aliases:
      - mauth
      - moodauthadmin

permissions:
  moodauth.admin:
    description: Accès aux commandes admin MoodAuth
    default: op