name: MoodAuth
version: 1.0
main: fr.moodcraft.auth.Main
api-version: '1.21'

commands:
  login:
    description: Se connecter à son compte MoodCraft
    usage: /login <motdepasse>
  register:
    description: Créer son compte MoodCraft
    usage: /register <motdepasse>
  changepassword:
    description: Changer son mot de passe MoodCraft
    usage: /changepassword <ancien> <nouveau>
  resetcompte:
    description: Réinitialiser le compte d'un joueur
    usage: /resetcompte <joueur>
    permission: moodauth.admin
  authadmin:
    description: Administration de la sécurité MoodAuth
    usage: /authadmin
    permission: moodauth.admin

permissions:
  moodauth.admin:
    description: Accès aux commandes administratives de MoodAuth
    default: op
