name: Build MoodAuth

on:
  workflow_dispatch:   # 🔥 bouton manuel
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      # 📥 Récupère le code
      - name: Checkout
        uses: actions/checkout@v4

      # ☕ Java 21
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # 📦 Cache Maven (plus rapide)
      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-

      # 🔨 Build
      - name: Build with Maven
        run: mvn clean package

      # 📤 Upload le .jar
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MoodAuth
          path: target/*.jar